#!/usr/bin/env ruby

require 'pathname'
require "optparse"
require_relative "../lib/omgcnb.rb"

options = {}
parser = OptionParser.new do |opts|
  opts.banner = <<~EOM
    Usage: omgcnb [argument] [options]

    Commands:
      - scan <dir>: Outpusts buildpacks and their dependencies for a given path

    Options:
  EOM

  opts.on("--exclude <dir>", "") do |v|
    options[:exclude] = v
  end

  opts.on("--allow-test", "") do
    options[:allow_test] = true
  end
end
parser.parse!


command = ARGV[0]
directory = ARGV[1]

case command
when 'scan'
  directory = Pathname(directory).expand_path
  exclude = if options[:exclude]
    [Pathname(options[:exclude]).expand_path]
  else
    []
  end
  if !options[:allow_test]
    exclude << directory.join("test")
    exclude << directory.join("spec")
  end

  buildpacks =  Omgcnb::BuildpacksFromDir.new(
    dir: directory,
    exclude: exclude
  ).buildpacks

  needs_release = Omgcnb::ResolveDependencies.new(buildpacks).solution
  puts
  puts "## Needs Release"
  puts
  needs_release.each_with_index do |buildpack, i|
    puts "#{i.next}) #{buildpack.name}"
    buildpack.changed_list.each do |line|
      puts "  #{line}"
    end
  end
  puts
  puts "## All Buildpacks"
  puts
  buildpacks.each do |b|
    Omgcnb::DisplayAllDeps.new(b).call
  end
when nil
  puts parser.help
  exit(1)
else
  puts "no such command #{command}"
  puts parser.help
  exit(1)
end
