#!/usr/bin/env ruby

require 'pathname'
require "optparse"
require_relative "../lib/omgcnb.rb"

options = {}
parser = OptionParser.new do |opts|
  opts.banner = <<~EOM
    Usage: omgcnb [argument] [options]

    Commands:
      - scan <dir>: Outpusts buildpacks and their dependencies for a given path

    Options:
  EOM

  opts.on("--exclude <dir>", "Skipps scanning directory") do |v|
    options[:exclude] = v
  end

  opts.on("--allow-test", "By default `<dir>/test` and `<dir>/spec` directories are skipped, use this flag to disable") do
    options[:allow_test] = true
  end
end
parser.parse!

command = ARGV[0]
directory = ARGV[1]

case command
when 'scan'
  exclude = if options[:exclude]
    [Pathname(options[:exclude]).expand_path]
  else
    []
  end

  Omgcnb::ScanCLI.new(
    dir: directory,
    exclude: exclude,
    allow_test: options[:allow_test]
  ).call()
when nil
  puts parser.help
  exit(1)
else
  puts "no such command #{command}"
  puts parser.help
  exit(1)
end
